language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

sudo: false

install:
    - composer self-update && composer --version
    - composer global require "fxp/composer-asset-plugin:1.0.0-beta3"
    - composer global require "codeception/codeception"
    - export PATH="$HOME/.composer/vendor/bin:$PATH"
    - composer install

script:
    - codecept run
